import type { Metadata } from "next";
import "./globals.css";
import { aeonik, satoshi } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Brooks Microfinance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${aeonik.variable}`}>{children}</body>
    </html>
  );
}
